version: "3"
services:
  redis:
    image: valkey/valkey:7.2-alpine
    container_name: toki_valkey
    restart: always
    ports: 
      - 6379:6379
    environment:
      REDIS_PORT: 6379
  postgresql:
    image: postgres
    container_name: toki_postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: toki
      POSTGRES_PASSWORD: toki
